site_name: Schemathesis
repo_url: https://github.com/schemathesis/schemathesis

nav:
  - Overview: index.md
  - How It Works: how-it-works.md
  - Getting Started: getting-started.md
  - Command-Line Interface: cli.md
  - Python Integration: python-integration.md
  - Continuous Integration: ci.md
  - Extending Schemathesis: extending.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md
  - Reference:
      - Configuration: reference/configuration.md
      - Command-Line Options: reference/cli.md
  - Resources: resources.md
  - FAQ: faq.md

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.footer
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/schemathesis/schemathesis
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/R9ASRAmHnA
      name: Discord

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: Copyright &copy; 2020-2025 Dmitry Dygalo & Schemathesis.io
